---
kind: pipeline
name: python-3-8
type: docker

steps:
- name: test
  image: carvk/java_python:openjdk15_python38
  commands:
  - pip install git+https://github.com/cknoll/yamlpyowl.git
  - cd scra-backend
  - pip install -r requirements.txt
  - pip install .
  - python -m unittest discover tests
  - cd ../django
  - pip install -r requirements.txt
  - export SCRA_USE_EXAMPLE_CONFIG=true
  - python3 manage.py test

# To save energy and resources ci should only run for a few branches
# Related section of the docs: https://docs.drone.io/pipeline/triggers/
# Strategy: push regularly to branch `develop` and occasionally to `develop_ci` (only when ci should run)
trigger:
  branch:
    - main
    - develop_ci
