# Generated by Django 3.1.1 on 2021-02-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_directive_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geographicentity',
            old_name='applying_direcitves',
            new_name='applying_directives',
        ),
    ]
