# Generated by Django 3.1.1 on 2021-03-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_directive_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="label",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
